### ISSUE TITLE
Suggested code changes

### ISSUE THREAD

**Issue by jrappen** [p3lim/sublime-hide-menu#1]
* menus are not part of the application window in macOS
* use `on_new_async` to not block the main thread

Compare: <http://www.sublimetext.com/docs/3/api_reference.html>

```py
#!/usr/bin/env python
# coding: utf-8


import sublime
import sublime_plugin


def hide_menu_in_all_windows():
    if sublime.platform() is not 'osx':
        for w in sublime.windows():
            if w.is_menu_visible():
                w.set_menu_visible(False)

# def plugin_loaded():
#     hide_menu_in_all_windows()


class HideMenu(sublime_plugin.EventListener):

    def on_new_async(self, view):
        hide_menu_in_all_windows()
```

**Comment by p3lim** [comment]
The blocking is necessary, without it the menu would show for a second on all new windows.

Otherwise great suggestions.

**Comment by p3lim** [comment]
https://github.com/p3lim/sublime-hide-menu/commit/a06162ba8ccc666d3e205771916a32c3fd68b479
